const cars = [
    // Sedan
    {
      id: 1,
      name: 'Toyota Corolla',
      category: 'Sedan',
      price: '$30/day',
      seats: 5,
      transmission: 'Automatic',
      image: '/src/assets/toyotacorola.jpg',
    },
    {
      id: 2,
      name: 'Honda Civic',
      category: 'Sedan',
      price: '$35/day',
      seats: 5,
      transmission: 'Automatic',
      image: '/src/assets/civic.jpg',
    },
    {
      id: 9,
      name: 'Nissan Altima',
      category: 'Sedan',
      price: '$45/day',
      seats: 5,
      transmission: 'Automatic',
      image: ' ',
    },
    {
      id: 10,
      name: 'Hyundai Elantra',
      category: 'Sedan',
      price: '$35/day',
      seats: 5,
      transmission: 'Automatic',
      image: 'https://www.hyundaiusa.com/us/en/images/vehicles/elantra/gallery/2022-elantra-gallery-16.jpg',
    },
    {
      id: 11,
      name: 'Kia Optima',
      category: 'Sedan',
      price: '$38/day',
      seats: 5,
      transmission: 'Automatic',
      image: 'https://www.kia.com/us/content/dam/kia/us/en/images/vehicles/optima/2020/2020-kia-optima-mojave-sand.jpg',
    },
    {
      id: 12,
      name: 'Mazda 3',
      category: 'Sedan',
      price: '$33/day',
      seats: 5,
      transmission: 'Manual',
      image: 'https://www.mazdausa.com/siteassets/vehicles/2022/m3/2022-mazda3-sedan-w2-2201-pp-c.jpg',
    },
  
    // Sports
    {
      id: 3,
      name: 'Ford Mustang',
      category: 'Sports',
      price: '$60/day',
      seats: 4,
      transmission: 'Manual',
      image: ' ',
    },
    {
      id: 4,
      name: 'Chevrolet Camaro',
      category: 'Sports',
      price: '$55/day',
      seats: 4,
      transmission: 'Automatic',
      image: 'https://www.chevrolet.com/content/dam/chevrolet/na/us/english/index/vehicles/2023/performance/camaro/mov/camaro-wild-cherry-tintcoat.jpg?imwidth=960',
    },
    {
      id: 21,
      name: 'Porsche 911',
      category: 'Sports',
      price: '$200/day',
      seats: 2,
      transmission: 'Manual',
      image: 'https://files.porsche.com/filestore/image/multimedia/none/modelseries-911-carrera-intro-image/normal/01a08e09-e407-11eb-80c1-005056bbdc38;sS;twebp/porsche-normal.webp',
    },
    {
      id: 22,
      name: 'Lamborghini Huracan',
      category: 'Sports',
      price: '$350/day',
      seats: 2,
      transmission: 'Automatic',
      image: 'https://www.lamborghini.com/sites/it-en/files/DAM/lamborghini/share%20img/Huracan-Model%20Page%20Header.jpg',
    },
  
    // Luxury
    {
      id: 5,
      name: 'BMW 3 Series',
      category: 'Luxury',
      price: '$70/day',
      seats: 5,
      transmission: 'Automatic',
      image: 'https://www.bmwusa.com/content/dam/bmw/marketUSA/bmwusa/3-series-sedan/2023/3-series-sedan.png',
    },
    {
      id: 6,
      name: 'Mercedes-Benz C-Class',
      category: 'Luxury',
      price: '$75/day',
      seats: 5,
      transmission: 'Automatic',
      image: 'https://www.mbusa.com/content/dam/mb-nafta/us/myco/my22/c/sedan/all-vehicles/2022-C-SEDAN-AVP-DR.png',
    },
    {
      id: 7,
      name: 'Audi A4',
      category: 'Luxury',
      price: '$65/day',
      seats: 5,
      transmission: 'Automatic',
      image: 'https://www.audiusa.com/content/dam/nemo/us/models/a4/a4my2021/1920x1080_A4_MY2021.jpg',
    },
    {
      id: 23,
      name: 'Lexus LS',
      category: 'Luxury',
      price: '$100/day',
      seats: 5,
      transmission: 'Automatic',
      image: 'https://www.lexus.com/cm-img/lexus-one/vehicles/2023/ls/2023-lexus-ls-gallery-exterior-003.jpg',
    },
  
    // Hatchback
    {
      id: 8,
      name: 'Volkswagen Golf',
      category: 'Hatchback',
      price: '$40/day',
      seats: 5,
      transmission: 'Manual',
      image: 'https://www.vw.com/content/dam/vwcom/2021-myb/vehicles/GTI/FWD-2-1/VW2021MY_GTI_Desktop_01.jpg',
    },
    {
      id: 24,
      name: 'Ford Focus',
      category: 'Hatchback',
      price: '$35/day',
      seats: 5,
      transmission: 'Automatic',
      image: ' ',
    },
    {
      id: 25,
      name: 'Chevrolet Spark',
      category: 'Hatchback',
      price: '$30/day',
      seats: 5,
      transmission: 'Manual',
      image: 'https://www.chevrolet.com/content/dam/chevrolet/na/us/english/index/vehicles/2021/cars/spark/mov/2021-spark-masthead-01.jpg',
    },
  
    // Electric
    {
      id: 14,
      name: 'Tesla Model 3',
      category: 'Electric',
      price: '$90/day',
      seats: 5,
      transmission: 'Automatic',
      image: 'https://www.tesla.com/sites/default/files/modelsx-new/social/model-3-social.jpg',
    },
    {
      id: 26,
      name: 'Nissan Leaf',
      category: 'Electric',
      price: '$50/day',
      seats: 5,
      transmission: 'Automatic',
      image: 'https://www.nissanusa.com/content/dam/Nissan/us/vehicles/leaf/2023/2023-nissan-leaf-my23-overview-01.jpg',
    },
    {
      id: 27,
      name: 'Chevrolet Bolt EV',
      category: 'Electric',
      price: '$55/day',
      seats: 5,
      transmission: 'Automatic',
      image: 'https://www.chevrolet.com/content/dam/chevrolet/na/us/english/index/vehicles/2021/cars/bolt-ev/mov/2021-bolt-ev-masthead-01.jpg',
    },
  
    // Hybrid
    {
      id: 15,
      name: 'Toyota Prius',
      category: 'Hybrid',
      price: '$40/day',
      seats: 5,
      transmission: 'Automatic',
      image: 'https://www.toyota.com/imgix/responsive/images/mlp/colorizer/2021/prius/4T3.png',
    },
    {
      id: 28,
      name: 'Honda Insight',
      category: 'Hybrid',
      price: '$45/day',
      seats: 5,
      transmission: 'Automatic',
      image: 'https://www.honda.com/content/dam/Honda/us/cars/insight/2021/overview/2021-Honda-Insight-Hybrid-Touring.jpg',
    },
    {
      id: 29,
      name: 'Hyundai Ioniq',
      category: 'Hybrid',
      price: '$42/day',
      seats: 5,
      transmission: 'Automatic',
      image: 'https://www.hyundaiusa.com/us/en/images/vehicles/2021/ioniq-hybrid/gallery/ioniq-hybrid-gallery-10.jpg',
    },
  
    // SUV
    {
      id: 13,
      name: 'Jeep Wrangler',
      category: 'SUV',
      price: '$50/day',
      seats: 5,
      transmission: 'Automatic',
      image: 'https://www.jeep.com/content/dam/fca-brands/na/jeep/en_us/2022/wrangler/vlp/2022-jeep-wrangler-vlp-exterior-hero-01.jpg',
    },
    {
      id: 16,
      name: 'Chevrolet Tahoe',
      category: 'SUV',
      price: '$65/day',
      seats: 7,
      transmission: 'Automatic',
      image: 'https://www.chevrolet.com/content/dam/chevrolet/na/us/english/index/vehicles/2021/suvs/tahoe/mov/01-images/2021-tahoe-masthead-01.jpg',
    },
    {
      id: 19,
      name: 'Honda CR-V',
      category: 'SUV',
      price: '$55/day',
      seats: 5,
      transmission: 'Automatic',
      image: 'https://automobiles.honda.com/-/media/Honda-Automobiles/Vehicles/2023/CR-V/01-vehicle-gallery/MY23-CR-V-VLP-Hero-1440x768.jpg',
    },
    {
      id: 20,
      name: 'Subaru Outback',
      category: 'SUV',
      price: '$60/day',
      seats: 5,
      transmission: 'Automatic',
      image: 'https://www.subaru.com/content/dam/subaru/vehicles/outback/2022/gallery/2022_Outback_gallery_01.jpg',
    },
    {
      id: 30,
      name: 'Toyota Highlander',
      category: 'SUV',
      price: '$70/day',
      seats: 7,
      transmission: 'Automatic',
      image: 'https://www.toyota.com/imgix/responsive/images/mlp/colorizer/2022/highlander/1J9.png',
    },
  
    // Truck
    {
      id: 17,
      name: 'Ford F-150',
      category: 'Truck',
      price: '$75/day',
      seats: 6,
      transmission: 'Automatic',
      image: ' ',
    },
    {
      id: 18,
      name: 'Ram 1500',
      category: 'Truck',
      price: '$70/day',
      seats: 6,
      transmission: 'Automatic',
      image: 'https://www.ramtrucks.com/content/dam/fca-brands/na/ramtrucks/en_us/2022/ram-1500/gallery/exterior/ram1500ext-gal1.jpg',
    },
    {
      id: 31,
      name: 'Chevrolet Silverado',
      category: 'Truck',
      price: '$80/day',
      seats: 6,
      transmission: 'Automatic',
      image: 'https://www.chevrolet.com/content/dam/chevrolet/na/us/english/index/vehicles/2021/trucks/silverado/mov/01-images/2021-silverado-masthead-01.jpg',
    },
  ];
  
  export default cars;
  