const cars = [
    {
      id: 1,
      name: 'Toyota Corolla',
      category: 'Sedan',
      price: '$30/day',
      seats: 5,
      transmission: 'Automatic',
      image: '/src/assets/toyotacorola.jpg',
    },
    {
      id: 2,
      name: 'Honda Civic',
      category: 'Sedan',
      price: '$35/day',
      seats: 5,
      transmission: 'Automatic',
      image: '/src/assets/civic.jpg',
    },
    {
      id: 3,
      name: 'Ford Mustang',
      category: 'Sports',
      price: '$60/day',
      seats: 4,
      transmission: 'Manual',
      image: 'https://www.ford.com/is/image/Ford/2023-Mustang-Mach1-PureMetal_Desktop_04?qlt=90&fmt=webp&wid=1440',
    },
    {
      id: 4,
      name: 'Chevrolet Camaro',
      category: 'Sports',
      price: '$55/day',
      seats: 4,
      transmission: 'Automatic',
      image: 'https://www.chevrolet.com/content/dam/chevrolet/na/us/english/index/vehicles/2023/performance/camaro/mov/camaro-wild-cherry-tintcoat.jpg?imwidth=960',
    },
    {
      id: 5,
      name: 'BMW 3 Series',
      category: 'Luxury',
      price: '$70/day',
      seats: 5,
      transmission: 'Automatic',
      image: 'https://www.bmwusa.com/content/dam/bmw/marketUSA/bmwusa/3-series-sedan/2023/3-series-sedan.png',
    },
    {
      id: 6,
      name: 'Mercedes-Benz C-Class',
      category: 'Luxury',
      price: '$75/day',
      seats: 5,
      transmission: 'Automatic',
      image: 'https://www.mbusa.com/content/dam/mb-nafta/us/myco/my22/c/sedan/all-vehicles/2022-C-SEDAN-AVP-DR.png',
    },
    {
      id: 7,
      name: 'Audi A4',
      category: 'Luxury',
      price: '$65/day',
      seats: 5,
      transmission: 'Automatic',
      image: 'https://www.audiusa.com/content/dam/nemo/us/models/a4/a4my2021/1920x1080_A4_MY2021.jpg',
    },
    {
      id: 8,
      name: 'Volkswagen Golf',
      category: 'Hatchback',
      price: '$40/day',
      seats: 5,
      transmission: 'Manual',
      image: 'https://www.vw.com/content/dam/vwcom/2021-myb/vehicles/GTI/FWD-2-1/VW2021MY_GTI_Desktop_01.jpg',
    },
    {
      id: 9,
      name: 'Nissan Altima',
      category: 'Sedan',
      price: '$45/day',
      seats: 5,
      transmission: 'Automatic',
      image: 'https://www.nissanusa.com/content/dam/Nissan/us/vehicles/altima/2023/altima%2023/23Altima_MYR_Hero.png',
    },
    {
      id: 10,
      name: 'Hyundai Elantra',
      category: 'Sedan',
      price: '$35/day',
      seats: 5,
      transmission: 'Automatic',
      image: 'https://www.hyundaiusa.com/us/en/images/vehicles/elantra/gallery/2022-elantra-gallery-16.jpg',
    },
    {
      id: 11,
      name: 'Kia Optima',
      category: 'Sedan',
      price: '$38/day',
      seats: 5,
      transmission: 'Automatic',
      image: 'https://www.kia.com/us/content/dam/kia/us/en/images/vehicles/optima/2020/2020-kia-optima-mojave-sand.jpg',
    },
    {
      id: 12,
      name: 'Mazda 3',
      category: 'Sedan',
      price: '$33/day',
      seats: 5,
      transmission: 'Manual',
      image: 'https://www.mazdausa.com/siteassets/vehicles/2022/m3/2022-mazda3-sedan-w2-2201-pp-c.jpg',
    },
  ];
  
  export default cars;
  